version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: lacrei-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lacrei-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lacrei-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: lacrei@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
